### ISSUE TITLE
Script works, but says "Sorry, try again"

### ISSUE THREAD

**Issue by MatrixManAtYrService** [b4b4r07/ssh-keyreg#2]
First of all, thank you for making this.  It's going to save me a lot of time.

Here is the output that I get:

    Enter host password for user 'MatrixManAtYrService':
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  1715  100   929  100   786   1026    868 --:--:-- --:--:-- --:--:--  1027
    The authenticity of host 'github.com (192.30.253.113)' can't be established.
    RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
    Are you sure you want to continue connecting (yes/no)? yes
    sorry, try again

The key appears in my account, but the output makes it seem like it didn't.  It's not so much of a problem, but I thought you might like to know.

**Comment by babarot** [comment]
Looks too stale. Closing but feel free to ask me if you have something. Thanks
